# Generated by Django 3.1.2 on 2020-11-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('rol', models.CharField(choices=[('Comisión', 'comision'), ('Investigador', 'investigador'), ('Estudiante investigador', 'estudiante_investigador')], max_length=50, null=True)),
            ],
        ),
    ]
